name: Captchafy
version: 1.1.0-TF
main: me.hockey.captchafy.Captchafy

commands:
  captchafy:
      
captchafy.command:
     description: Allow a player to use the captchafy command.
     default: op